#!/bin/bash

d=$(cd "$(dirname "$0")" || exit; pwd)

usage() {
    cat <<EOS > /dev/stderr
Suggest outbound licenses based on the licenses of the dependencies.

gh licensecheck TARGET [FLAGS]
  Extract dependencies which hosted on GitHub, suggest licenses based on them.
  See gh licensecheck outbound --help for FLAGS.

gh licensecheck outbound [FLAGS]
  Read dependency repos from stdin, suggest outbound licenses.
  Repo is a string like astral-sh/uv (owner/repo).
  See gh licensecheck outbound --help for FLAGS.

gh licensecheck extract TARGET
  Extract direct dependencies which hosted on GitHub.

TARGET: go, pipenv, rust

The Dependencies are read from the following file:
- go: go.mod
- pipenv: Pipfile
- rust: Cargo.toml
EOS
}

category="$1"
shift
case "$category" in
    extract) "${d}/extract.sh" "$@" ;;
    outbound) "${d}/outbound" "$@" ;;
    "" | "help" | "--help" | "-h") usage ;;
    *) "${d}/extract.sh" "$category" | "${d}/outbound" "$@" ;;
esac
