[project]
name = "gh-licensecheck"
version = "0.1.0"
description = "Suggest outbound licenses based on the licenses of the dependencies."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flict>=1.3.0",
    "ruff>=0.7.4",
]
